---
- name: Configuration du routeur CSR1000
  hosts: csr1000
  gather_facts: no

  tasks:

    - name: Configuration IP des interfaces
      cisco.ios.ios_l3_interfaces:
        config:
          - name: GigabitEthernet1
            ipv4:
              - dhcp:
                  enable: true
          - name: GigabitEthernet2
            ipv4:
              - address: 192.168.2.1/24
          - name: GigabitEthernet3
            ipv4:
              - address: 192.168.3.1/24
          - name: GigabitEthernet4
            ipv4:
              - address: 192.168.4.1/24
        state: merged

    - name: Activation et description des interfaces
      cisco.ios.ios_interfaces:
        config:
          - name: GigabitEthernet1
            description: WAN
            enabled: true
          - name: GigabitEthernet2
            description: LAN_ENTREPRISE
            enabled: true
          - name: GigabitEthernet3
            description: LAN_DMZ
            enabled: true
          - name: GigabitEthernet4
            description: ADMIN
            enabled: true
        state: merged

    - name: Suppression du pool DHCP existant (évite les erreurs)
      cisco.ios.ios_config:
        lines:
          - no ip dhcp pool LAN_ENTREPRISE
      ignore_errors: yes

    - name: Configuration du serveur DHCP
      cisco.ios.ios_config:
        lines:
          - ip dhcp pool LAN_ENTREPRISE
          - network 192.168.2.0 255.255.255.0
          - default-router 192.168.2.1
          - dns-server 8.8.8.8



    - name: Configuration ip nat outside sur WAN
      cisco.ios.ios_config:
        parents: interface GigabitEthernet1
        lines:
          - ip nat outside

    - name: Configuration ip nat inside sur LAN (loop)
      cisco.ios.ios_config:
        parents: "interface GigabitEthernet{{ item }}"
        lines:
          - ip nat inside
      loop:
        - 2
        - 3
        - 4

    - name: Configuration ACL pour le NAT
      cisco.ios.ios_config:
        lines:
          - access-list 1 permit 192.168.2.0 0.0.0.255
          - access-list 1 permit 192.168.3.0 0.0.0.255
          - access-list 1 permit 192.168.4.0 0.0.0.255

    - name: Activation du PAT dynamique (overload)
      cisco.ios.ios_config:
        lines:
          - ip nat inside source list 1 interface GigabitEthernet1 overload



    - name: PAT par port - Serveur Web (192.168.3.2:80 -> WAN:80)
      cisco.ios.ios_config:
        lines:
          - ip nat inside source static tcp 192.168.3.2 80 interface GigabitEthernet1 80

    - name: PAT par port - Serveur SSH (192.168.4.2:22 -> WAN:2222)
      cisco.ios.ios_config:
        lines:
          - ip nat inside source static tcp 192.168.4.2 22 interface GigabitEthernet1 2222

